package tapdkp;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author nabilahanas
 */
public class paket extends javax.swing.JFrame {

    private int harga;
    
    public paket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblnomor = new javax.swing.JLabel();
        txtnomor = new javax.swing.JTextField();
        lblnomor2 = new javax.swing.JLabel();
        lblpaket = new javax.swing.JLabel();
        cmbpaket = new javax.swing.JComboBox<>();
        lblpaket2 = new javax.swing.JLabel();
        lblharga = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        lbluang = new javax.swing.JLabel();
        txtuang = new javax.swing.JTextField();
        lbluang2 = new javax.swing.JLabel();
        beliButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paket Internet Bulanan");
        setBackground(new java.awt.Color(220, 36, 32));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(220, 32, 36));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("emPATI");

        lblnomor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblnomor.setForeground(new java.awt.Color(255, 255, 255));
        lblnomor.setText("Nomor Telepon");

        txtnomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomorActionPerformed(evt);
            }
        });
        txtnomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomorKeyPressed(evt);
            }
        });

        lblpaket.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblpaket.setForeground(new java.awt.Color(255, 255, 255));
        lblpaket.setText("Paket Internet");

        cmbpaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Paket", "35GB/1Bln", "15GB/1Bln", "5GB/1Bln", "3GB/1Bln" }));
        cmbpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpaketActionPerformed(evt);
            }
        });

        lblharga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblharga.setForeground(new java.awt.Color(255, 255, 255));
        lblharga.setText("Harga Paket");

        lbluang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbluang.setForeground(new java.awt.Color(255, 255, 255));
        lbluang.setText("Uang Pembayaran");

        txtuang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuangKeyPressed(evt);
            }
        });

        beliButton.setText("Beli");
        beliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliButtonActionPerformed(evt);
            }
        });

        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(beliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(keluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnomor)
                            .addComponent(lblpaket)
                            .addComponent(lblharga))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtharga)
                            .addComponent(cmbpaket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnomor2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomor)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblpaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbluang)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lbluang2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtuang, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomor)
                    .addComponent(txtnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnomor2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpaket)
                    .addComponent(cmbpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblharga)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluang)
                    .addComponent(txtuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbluang2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beliButton)
                    .addComponent(batalButton)
                    .addComponent(keluarButton))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomorActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_txtnomorActionPerformed

    private void txtnomorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomorKeyPressed
        String nomor = txtnomor.getText();
        int length = nomor.length();
        char c = evt.getKeyChar();
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9') {
                if(length<12){
                    txtnomor.setEditable(true);
                }
                else{
                    txtnomor.setEditable(false);
                }
            }
            else{
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE) {
                    txtnomor.setEditable(true);
                }
                else{
                    txtnomor.setEditable(false);
                }
            }
    }//GEN-LAST:event_txtnomorKeyPressed

    private void cmbpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpaketActionPerformed
        String paket = (String) cmbpaket.getSelectedItem();
        switch (paket) {
            case "Pilih Paket":
                lblpaket2.setText("Anda belum memilih paket");
                harga = 0;
                break;
            case "35GB/1Bln":
                lblpaket2.setText("");                
                harga = 85000;
                break;
            case "15GB/1Bln":
                lblpaket2.setText("");                
                harga = 65000;
                break;
            case "5GB/1Bln":
                lblpaket2.setText("");                
                harga = 40000;
                break;
            case "3GB/1Bln":
                lblpaket2.setText("");                
                harga = 30000;
                break;
            }
                txtharga.setText(""+Integer.toString(harga));
    }//GEN-LAST:event_cmbpaketActionPerformed

    private void beliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliButtonActionPerformed
        int bayar = Integer.parseInt(txtuang.getText());
        int hpaket = Integer.parseInt(txtharga.getText());
        int kembali = bayar - hpaket;
        berlaku tgl = new berlaku();
        tgl.setBerlaku("30 Juni 2021.");
        if (bayar >= hpaket) {
            JOptionPane.showMessageDialog(null, "Selamat! Paket Internet " + cmbpaket.getSelectedItem()
                    + " untuk pelanggan " + txtnomor.getText() + " telah aktif." 
                    + "\nBerlaku hingga " + tgl.getberlaku()
                    + "\nAnda memiliki uang kembalian sebesar Rp" + kembali
                    + "\nTerima kasih telah melakukan transaksi.", "", JOptionPane.PLAIN_MESSAGE);
            txtnomor.setText("");
            cmbpaket.setSelectedIndex(0);
            txtharga.setText("");
            txtuang.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Transaksi gagal. \n" + "Uang pembayaran tidak mencukupi", "", JOptionPane.PLAIN_MESSAGE);            
        }     
    }//GEN-LAST:event_beliButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        txtnomor.setText("");
        cmbpaket.setSelectedIndex(0);
        txtharga.setText("");
        txtuang.setText("");       
    }//GEN-LAST:event_batalButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void txtuangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangKeyPressed
        String uang = txtuang.getText();
        int length = uang.length();
        char c = evt.getKeyChar();
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9') {
                if(length<6){
                    txtuang.setEditable(true);
                }
                else{
                    txtuang.setEditable(false);
                }
            }
            else{
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE) {
                    txtuang.setEditable(true);
                }
                else{
                    txtuang.setEditable(false);
                }
            }
    }//GEN-LAST:event_txtuangKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private javax.swing.JButton beliButton;
    private javax.swing.JComboBox<String> cmbpaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluarButton;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lblnomor;
    private javax.swing.JLabel lblnomor2;
    private javax.swing.JLabel lblpaket;
    private javax.swing.JLabel lblpaket2;
    private javax.swing.JLabel lbluang;
    private javax.swing.JLabel lbluang2;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtnomor;
    private javax.swing.JTextField txtuang;
    // End of variables declaration//GEN-END:variables
}
